### ISSUE TITLE
Missed Turn - Reble Route Itallian Villa Sprint Loop

### ISSUE THREAD

**Issue by PhilipAmos** [sandermvanvliet/RoadCaptain#102]
**Describe the issue**
I created the attched route which is for the Itallian Villa Sprint Loop Reble Route and it looked live RoadCaptain lots track of where I was when going along the sprint (Italian villas loop 4 section) as the progress bar stopped progressing and it missed the turn.

I tried again ad it was obvious it was going to miss the turn so I manually made the turns to complete a few loops and Road Captain wasn't able to recover.

My brother also tried the file on his computer and had the same issue.

**Application details:**
To help troubleshoot the issue please provide:
- Zwift version - 1.29 (latest version)
- Zwift device Windows 11 laptop
- Road Captain version 0.6.7.0

**Additional info**
To help troubleshoot the issue please attach:
- The route file you used - Uploaded, renamed to a TXT file
- The RoadCaptain log files (see the directory: `%userprofile%\AppData\Local\Codenizer BV\RoadCaptain`)
- Last Zwift log file (usually these live here: `My Documents\Zwift\Logs`)

If you have a screenshot or screen recording of the issue that always helps :+1:
[Rebel Route - Italian Villa Sprint Loop.TXT](https://github.com/sandermvanvliet/RoadCaptain/files/9594308/Rebel.Route.-.Italian.Villa.Sprint.Loop.TXT)

**Comment by sandermvanvliet** [comment]
Thanks for reporting. I’m working on a bunch of improvements for the positioning algorithm so I’ll test this one too with the improved code 👍

**Comment by sandermvanvliet** [comment]
Seems that with all the changes I've made this is working nicely now:
![image](https://user-images.githubusercontent.com/2393265/192311814-51bc8c40-8819-467f-8209-7f9124a0d8fc.png)

I've had it running for a few loops and it stays on route now.

I'm hoping to release a new version shortly, if you want I can create a preview build for you to try out.

**Comment by sandermvanvliet** [comment]
Have a look here: https://github.com/sandermvanvliet/RoadCaptain/releases/tag/untagged-6ef08bc358a0cd448d36

**Comment by PhilipAmos** [comment]
Hi, I can't seem to get the download link to work, "404, this is not the web page you are looking for".

**Comment by sandermvanvliet** [comment]
Should work now!
Sorry about that, forgot to publish it properly…

**Comment by PhilipAmos** [comment]
The link here still isn't working but I can see you have added 0.6.8.0 (Pre Release) to the Releases area.  Is it the same version?

**Comment by sandermvanvliet** [comment]
That’s the one yeah

**Comment by sandermvanvliet** [comment]
Correct link: https://github.com/sandermvanvliet/RoadCaptain/releases/tag/0.6.8.0

**Comment by PhilipAmos** [comment]
I tried with the new 0.6.8.0 (Pre Release) and Zwift version 1.29.1 and it didn't work.  It doesn't look like RoadCaptain loaded correctly.  It went through he usual steps of waiting for me to load Zwift and then start the correct course and then the interface went blank.

[roadcaptain-log-2022-05-28T215038.log](https://github.com/sandermvanvliet/RoadCaptain/files/9668326/roadcaptain-log-2022-05-28T215038.lo
![Screenshot 2022-09-28 183435](https://user-images.githubusercontent.com/106473361/192870488-cc4d034d-e810-4534-b42d-899c5db2f5c4.png)
g)

Cheers
Philip

**Comment by sandermvanvliet** [comment]
Bummer!
Do you perhaps have a file called something like `positions-2022-09-28_090537.log` in the same directory where the other log files are?

**Comment by PhilipAmos** [comment]
I don't and looking at it the log file I uploaded was from the 28th May.  I don't seem to have any log file from yesterday.  I will try and test again and see what happens.

**Comment by sandermvanvliet** [comment]
I did see that this happens when no position update has been sent by the game yet.
Also it's something that I broke earlier this week apparently, the current/next segment is now only shown when the route is in progress but that's not very helpful when you start the route but haven't moved in-game yet...

**Comment by sandermvanvliet** [comment]
@PhilipAmos so I’ve been banging my head against a really annoying and tricky issue where an error was thrown somewhere deep in the UI framework. 

It has taken me close to a week to figure out what was causing it and while I don’t know exactly what triggers it I’ve been able to make it go away…. finally.

Anyway, good news. Getting closer to a new release 👌

**Comment by sandermvanvliet** [comment]
Just published another pre-release build that you can try: https://github.com/sandermvanvliet/RoadCaptain/releases/tag/0.6.8.0

**Comment by PhilipAmos** [comment]
Still no Joy.  On my main laptop I had the same issue with no information in Road Captain after starting the route.

On my other laptop it loaded but it missed the first turn.  It looks like the progress bar stopped and didn't make it to 1.4km.  I then quit Zwift and Road C
[positions-2022-10-04_190806.log](https://github.com/sandermvanvliet/RoadCaptain/files/9709917/positions-2022-10-04_190806.log)
[roadcaptain-runner-log-2022-10-04T190601.log](https://github.com/sandermvanvliet/RoadCaptain/files/9709918/roadcaptain-runner-log-2022-10-04T190601.log)
aptain and started again and it made the first turn but while going over the sprint again the progress bar stopped moving.

I did grab a screenshot
![Missed First Turn](https://user-images.githubusercontent.com/106473361/193904268-f3df7cd4-8820-4a81-b1f4-c035644ca508.jpg)

**Comment by PhilipAmos** [comment]
Here are the logs for the first attempt on my other laptop which match with the screenshot on previous post.
[positions-2022-10-04_185520.log](https://github.com/sandermvanvliet/RoadCaptain/files/9709959/positions-2022-10-04_185520.log)
[roadcaptain-runner-log-2022-10-04T185210.log](https://github.com/sandermvanvliet/RoadCaptain/files/9709960/roadcaptain-runner-log-2022-10-04T185210.log)

**Comment by sandermvanvliet** [comment]
I’ll take a look tomorrow. 
This is driving me nuts, I’ve now tested this particular route so many times without problems on my machine that you would _think_ it’s just good to go 🤷‍♂️
Apparently not 😑

Anyway thank you so much for your patience and your help in testing this 👌

**Comment by sandermvanvliet** [comment]
> Here are the logs for the first attempt on my other laptop which match with the screenshot on previous post. [positions-2022-10-04_185520.log](https://github.com/sandermvanvliet/RoadCaptain/files/9709959/positions-2022-10-04_185520.log) [roadcaptain-runner-log-2022-10-04T185210.log](https://github.com/sandermvanvliet/RoadCaptain/files/9709960/roadcaptain-runner-log-2022-10-04T185210.log)

Apparently in this case what I can see is that Road Captain is re-initiating the Zwift -> Road Captain link more times than is necessary. That may cause the connection to be lost which is what you've described.

**Comment by sandermvanvliet** [comment]
@PhilipAmos quick question: are you running Zwift on one machine and RoadCaptain on another or both on the same machine?

**Comment by PhilipAmos** [comment]
Both on the same machine.

**Comment by sandermvanvliet** [comment]
How do you connect your trainer? Via bluetooth/ANT+ on the machine running Zwift or via the Zwift Companion?

**Comment by PhilipAmos** [comment]
I have just tested with 2 laptops (one with Zwift and one with RoadCaptain) and it made the first turn but then lost track again during the Sprint area.

Normally I use Ant+ dongle on my Laptop when using Zwift and pair Kickr bike directly.  For some of this testing like my quick test just now I was using the SimulANT+ program that I previously mentioned to you and this was running on the laptop I had RoadCaptain on.

**Comment by sandermvanvliet** [comment]
I've just identified an issue where the connection wouldn't be properly initialized if RoadCaptain is running but Zwift exits (or closes the connection).
In that situation the only messages that come in from Zwift to RoadCaptain are "keep alive" ones, so it appears there is a valid link but in fact no position data is being sent.

If you have the logs + position logs from your last test that would be great :+1:

**Comment by PhilipAmos** [comment]
Here are the files from my test with 2 laptops yesterday.  I forgot where they were located and was looking in the c:\Users\email\AppData\Local\Codenizer BV folder and not the installation folder.

[positions-2022-10-07_123707.log](https://github.com/sandermvanvliet/RoadCaptain/files/9738829/positions-2022-10-07_123707.log)
[roadcaptain-runner-log-2022-10-07T123509.log](https://github.com/sandermvanvliet/RoadCaptain/files/9738830/roadcaptain-runner-log-2022-10-07T123509.log)

**Comment by sandermvanvliet** [comment]
> Here are the files from my test with 2 laptops yesterday. I forgot where they were located and was looking in the c:\Users\email\AppData\Local\Codenizer BV folder and not the installation folder.

Oh man, I just thought "Why are they in the installation folder?" and realised that for _debug_ builds it drops the log file in the startup location of the app and not the AppData one 😐😐

**Comment by sandermvanvliet** [comment]
@PhilipAmos got a new test release ready to go if you want to test it: https://github.com/sandermvanvliet/RoadCaptain/releases/tag/0.6.8.1
This release adds a lot more diagnostic info on the Zwift connection and data receives which should allow me to (hopefully finally) figure out what's happening on your installation :+1:

**Comment by PhilipAmos** [comment]
Hi, I have been doing some playing this evening using SimulANT+, Zwift and RoadCaptain on the same machine and it looks to be working.

I was reading the Requirements and it states you need a Firewall rule in the Private Profile.  I checked and I had 4 RoadRunner Rules (2 UDP and 2 TCP), 2 of them were pointing to what I assume was an old EXE file.  All 4 Rules were on the Public Profile and NOT Private Profile.

I deleted all 4 Rules.  I then uninstalled and re-installed Road Captain but the Rules weren't created automatically as I expected.  No problem, I created them myself and selected both the Private and Public Profiles and now it seems to be working.

I will do some more testing tomorrow with my other laptop and also running Road Captain and Zwift on different machines.

**Comment by sandermvanvliet** [comment]
Oh wow that’s some proper digging you did 👍

It’s true that the installer doesn’t create those rules automatically. I haven’t figured out how to do that but I’ll create an issue for it to track it for an upcoming release.

Really happy that it seems to be working for you now!

**Comment by PhilipAmos** [comment]
I have been playing with my newer laptop today which wasn't working and the issue here was Permissions over the Road Captain installation directory in addition to the Firewall Rule mentioned above.

I previously noticed that there were no Log or Position files created on this Laptop and after fixing the Firewall Road Captain would connect but would say "Entered Game, Start Pedaling!".  The fix here was to grant the Users group Full Control (Modify will probably also work) over the C:\program files (x86)\codenizer bv\RoadCaptain Folder so that the Log and Position files could be created and now this machine seems to be happy as well.

**Comment by sandermvanvliet** [comment]
Yeah that log file writing is a bit shitty in the debug builds.
I've got it set up so that when I'm running a debug build (like in Visual Studio) it outputs to the current directory which is under my source tree so that's fine. However with the debug builds I'm publishing that doesn't work because they are proper installers and as you've found out Program Files isn't writable and RoadCaptain shouldn't write there in the first place.

I'll cover that as well so that the Full Control permissions shouldn't be necessary anymore.

**Comment by sandermvanvliet** [comment]
Sorted the logging business out: 0486ad6cff9c3ddcd56829df4b58d1144390be9a

**Comment by sandermvanvliet** [comment]
@PhilipAmos I’m going to close this issue as you’ve indicated it’s now working for you. 
Feel free to re-open or create another issue if you find any more problems. 
Currently I’m putting together some final things so that I can release version 0.6.9.0 that will include all these fixes.
